Fixed rollup config
vuejs/vuejs.org pull request #2079
Opened 2019-03-21 18:27 UTC by romanslonov

Current rollup config is not working now. According to this https://github.com/vuejs/rollup-plugin-vue/commit/fd3dfb9a4440b13b220fb2dc535506274280fa0c commit, it requires 'rollup-plugin-commonjs' plugin as well. Without that, we got "Error: 'default' is not exported by node_modules/vue-runtime-helpers/dist/normalize-component.js" error.

2019-03-22 08:00 UTC, phanan requested changes

2019-03-22 08:00 UTC, phanan commented on src/v2/cookbook/packaging-sfc-for-npm.md
> +import commonjs from 'rollup-plugin-commonjs';
We need an empty line after this.

2019-04-29 03:20 UTC, romanslonov commented
@phanan ?

2019-04-29 04:31 UTC, znck commented
@phanan There is an example configs page on rollup docs. Maybe we can link it here.

2025-09-24 06:03 UTC, closed without merging